---
title: "Sample Quarto Presentation with Revealjs"
format:
  revealjs:
    theme: [default, custom.scss]
    logo: nebraska-n.jpg
    fontsize: 1.6em
    callout-icon: false
    scrollable: true
    fig-dpi: 400
    fig-align: left
execute:
  echo: false
  message: false
  warning: false
---


```{r}
#| include: false
library(ggplot2)
library(dplyr)
```

# Section title

## Slide title

```{r}
#| echo: true
#| fig-width: 5
#| fig-height: 3
#| out-width: 5in
#| out-height: 3in

ggplot(data = mtcars) +
  geom_point(aes(y = mpg, x = cyl))
```

# New section title

## Slide with tabsets

::: {.panel-tabset}

### Tab 1

### Tab 2

### Tab 3

:::
<!--end of panel-->

## Slide with nested tabsets

::: {.panel-tabset}

### Tab 1

::: {.panel-tabset}

#### Tab 1

#### Tab 2

#### Tab 3

#### Tab 4

:::
<!--end of panel-->

### Tab 2

### Tab 3

:::
<!--end of panel-->

## Slide with a figure

```{r}
#| fig-width: 5
#| fig-height: 6
#| out-width: 5in
#| out-height: 6in
#| fig-align: left
ggplot(data = mtcars) +
  geom_point(aes(y = mpg, x = cyl))
```

## Slide with a table

```{r}
gt::gt(mtcars)
```

## Slide with an incremental list

- collect data
- run statistical analysis
- report

::: {.incremental}
- collect data
- run statistical analysis
- report
:::

## Slide with columns

::: {.columns}

::: {.column width="50%"}
```{r}
#| out-width: 50%
ggplot(data = mtcars) +
  geom_point(aes(y = mpg,  x = cyl))
```
:::
<!--end of the 1st column-->

::: {.column width="50%"}
```{r}
#| fig-cap: "Nice plot title"
ggplot(data = mtcars) +
  geom_point(aes(y = mpg,  x = disp))
```
:::

<!--end of the 2nd column-->

:::
<!--end of the columns-->


::: {.columns}

::: {.column width="50%"}
```{r}
#| out-width: 100%
ggplot(data = mtcars) +
  geom_point(aes(y = mpg,  x = cyl))
```
:::
<!--end of the 1st column-->

::: {.column width="50%"}
```{r}
#| fig-cap: "Nice plot title"
ggplot(data = mtcars) +
  geom_point(aes(y = mpg,  x = disp))
```
:::

<!--end of the 2nd column-->

:::
<!--end of the columns-->




## Slide with regression results

```{r}
#| echo: true
#| eval: false
reg <- lm(mpg ~ cyl + disp, data = mtcars) 

modelsummary::modelsummary(reg)
```